# Generated by Django 4.2.17 on 2024-12-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roll',
            new_name='SingleRoll',
        ),
    ]
